### ISSUE TITLE
Elemens repositioning error in Window demo

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#11]
See video
https://www.youtube.com/watch?v=xCY7v9DBc7I

Regards, Alexey Knyshev

**Comment by novembermonk** [comment]
This was not really a bug but part of the way items are laid out by default, which is centered in Y direction. Fixed in 7ad73ca

**Comment by hugoam** [comment]
This was not really a bug but part of the way items are laid out by default, which is centered in Y direction. Fixed in 7ad73ca
