### ISSUE TITLE
Filtered demo crash

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#14]
Crash reproduction video:
https://www.youtube.com/watch?v=OzHMTXk9bs8

open Filtered demo -> open Window demo -> put \* as filter in TypeIn -> close Window demo -> clear filer -> open Window demo -> put \* as filter in TypeIn -> SEGFAULT

Rearads, Alexey Knyshev

**Comment by hugoam** [comment]
Reproduced. I'll try to find the cause.

**Comment by hugoam** [comment]
Found it ! Should be fixed in e3b74fc
