### ISSUE TITLE
Combo box unexpected resizing and flickering on current item changing

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#15]
See video:
https://www.youtube.com/watch?v=xsOf9IKryDs

I detected some flickering and size changing when selecting combobox items.

Regards, Alexey Knyshev

**Comment by hugoam** [comment]
Most of these (except the segfault) should have been solved in really recent commits (yesterday night)
Please update and report back if they persist
There is a layout error in the filtered combobox though, which I'll try to resolve

**Comment by hugoam** [comment]
Should be fixed in d42ff46

**Comment by alexeyknyshev** [comment]
Done, Thx a lot!
