### ISSUE TITLE
Filtered demo crash 2

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#20]
Crash when reproducing with sequence:
open Filtered List demo -> put \* as filter -> clear filter by backspace -> click on the right side of TypeIn (which makes cursor to move by one symbol to right size) -> press Enter -> craaaash
https://www.youtube.com/watch?v=mEw4YkeA54o
(don't forget about enabling anotations, all my videos use anotations)

gdb backtrace:

> (gdb) bt
> 0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:152
> 1  0x00007ffff63e404d in copy (__n=18446744073709282239, __s2=<optimized out>, __s1=<optimized out>)
>     at /scratch/packages/gcc/4.9/gcc-4.9-4.9.2/build/x86_64-linux-gnu/libstdc++-v3/include/bits/char_traits.h:275
> 2  _M_copy (__n=18446744073709282239, __s=<optimized out>, __d=<optimized out>)
>     at /scratch/packages/gcc/4.9/gcc-4.9-4.9.2/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:361
> 3  std::string::_M_mutate (this=this@entry=0xff5aa0, __pos=__pos@entry=269377, __len1=<optimized out>, 
>     __len2=__len2@entry=1)
>     at /scratch/packages/gcc/4.9/gcc-4.9-4.9.2/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:484
> 4  0x00007ffff63e4394 in std::string::_M_replace_aux (this=0xff5aa0, __pos1=269377, __n1=<optimized out>, __n2=1, 
>     __c=<optimized out>)
>     at /scratch/packages/gcc/4.9/gcc-4.9-4.9.2/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:672
> 5  0x00007ffff63e4482 in std::string::insert (this=0xff5aa0, __p=..., __c=<optimized out>)
>     at /scratch/packages/gcc/4.9/gcc-4.9-4.9.2/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1359
> 6  0x00007ffff79fe378 in mk::TypeIn::insert (this=0xff5a40, c=10 '\n')
>     at /home/alexey/dev/src/kiui/src/Ui/Widget/mkTypeIn.cpp:92
> 7  0x00007ffff79fe893 in mk::TypeIn::keyDown (this=0xff5a40, code=mk::KC_RETURN, c=0 '\000')
>     at /home/alexey/dev/src/kiui/src/Ui/Widget/mkTypeIn.cpp:149
> 8  0x00007ffff7a0b8ea in mk::RootSheet::keyDown (this=0xe74b80, code=mk::KC_RETURN, c=0 '\000')
>     at /home/alexey/dev/src/kiui/src/Ui/Widget/mkRootSheet.cpp:144
> 9  0x00007ffff7ac6a2e in mk::UiWindow::dispatchKeyPressed (this=0xe4f7b0, key=mk::KC_RETURN, c=0 '\000')
>     at /home/alexey/dev/src/kiui/src/Ui/mkUiWindow.cpp:129
> 10 0x00007ffff7abdbb6 in mk::GlWindow::injectKey (this=0x7fffffffdf30, key=257, scancode=36, action=1, mods=0)
>     at /home/alexey/dev/src/kiui/src/Ui/Nano/mkGlWindow.cpp:324
> 11 0x00007ffff7abcfe7 in mk::GlWindow::<lambda(GLFWwindow*, int, int, int, int)>::operator()(GLFWwindow _, int, int, int, int) const (__closure=0x0, w=0x650bf0, key=257, scancode=36, action=1, mods=0)
>     at /home/alexey/dev/src/kiui/src/Ui/Nano/mkGlWindow.cpp:205
> 12 0x00007ffff7abd026 in mk::GlWindow::<lambda(GLFWwindow_, int, int, int, int)>::_FUN(GLFWwindow *, int, int, int, int) () at /home/alexey/dev/src/kiui/src/Ui/Nano/mkGlWindow.cpp:205
> 13 0x00007ffff663c3a4 in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
> 14 0x00007ffff7abd797 in mk::GlWindow::renderFrame (this=0x7fffffffdf30)
>     at /home/alexey/dev/src/kiui/src/Ui/Nano/mkGlWindow.cpp:275
> 15 0x000000000041e1a7 in main (argc=1, argv=0x7fffffffe0c8) at /home/alexey/dev/src/kiui/example/example.cpp:44

Regards, Alexey Knyshev

**Comment by novembermonk** [comment]
Cannot reproduce :/
Are you sure you pulled the change where I supposedly fixed this ? e3b74fc

**Comment by hugoam** [comment]
Cannot reproduce. My only explanation is you must be running an exe that is not up to date to the latest changes.

**Comment by alexeyknyshev** [comment]
Yeap, wrong branch. This is a signal to go to bed :zzz: 
Sorry for your time
