### ISSUE TITLE
[Enchantment] Make int/uint overflow optional in TypeIn

### ISSUE THREAD

**Issue by alexeyknyshev** [novembermonk/kiui#23]
Is it possible to implement it without inheritance?

Reagards, Alexey Knyshev

**Comment by hugoam** [comment]
I don't understand the question.
You mean prevent entering a value that is higher than MAX_INT for example ?

**Comment by alexeyknyshev** [comment]
In qt for example increment button disables when you reach maximum value of representing type

BTW I think it requires numeric specific TypeIn with API such:

> void setMaximum(const T &max)
> void setMinimum(const T &min)
> void setRange(const T& min, const T &max)

and getters

see:
http://doc.qt.io/qt-4.8/qspinbox.html
http://doc.qt.io/qt-4.8/qdoublespinbox.html

**Comment by hugoam** [comment]
Yes, this will be taken care of. 
The sliders already have a min max values in the Stat parameter that they take, it's just a matter of "moving" that feature to TypeIn also.

**Comment by hugoam** [comment]
Fixed in da79125
